# Generated by Django 4.1.7 on 2023-03-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apologizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apologizing', models.CharField(max_length=120, verbose_name='Apologizing')),
            ],
        ),
        migrations.CreateModel(
            name='AskingTheReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_reason', models.CharField(max_length=120, verbose_name='AskingTheReason')),
            ],
        ),
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending', models.CharField(max_length=120, verbose_name='Ending')),
            ],
        ),
        migrations.CreateModel(
            name='Tail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail', models.CharField(max_length=120, verbose_name='The most end part')),
            ],
        ),
        migrations.CreateModel(
            name='Thanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanking', models.CharField(max_length=120, verbose_name='Thanking')),
            ],
        ),
    ]
