# Generated by Django 4.1.7 on 2023-03-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroses', '0004_alter_apologizing_apologizing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.TextField(max_length=5000, verbose_name='The most end part')),
            ],
        ),
    ]
