# Generated by Django 4.1.7 on 2023-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroses', '0005_descriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_pal_refund', models.TextField(max_length=5000, verbose_name='PayPal refund')),
            ],
        ),
        migrations.CreateModel(
            name='TransferToBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_to_billing', models.TextField(max_length=5000, verbose_name='Transfer to billing')),
            ],
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='descriptor',
            field=models.TextField(max_length=5000, verbose_name='Descriptor'),
        ),
    ]
