# Generated by Django 4.1.7 on 2023-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroses', '0006_paypalrefund_transfertobilling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfraidNotCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afraid_not_cancel', models.TextField(max_length=5000, verbose_name='Afraid not cancel')),
            ],
        ),
        migrations.CreateModel(
            name='BadMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_meals', models.TextField(max_length=5000, verbose_name='Bad Meals')),
            ],
        ),
        migrations.CreateModel(
            name='BadWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_workouts', models.TextField(max_length=5000, verbose_name='bad workouts')),
            ],
        ),
        migrations.CreateModel(
            name='NoFreeTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_free_trial', models.TextField(max_length=5000, verbose_name='No free trial')),
            ],
        ),
        migrations.CreateModel(
            name='NoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_time', models.TextField(max_length=5000, verbose_name='No Time')),
            ],
        ),
    ]
