# Generated by Django 4.1.7 on 2023-03-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroses', '0007_afraidnotcancel_badmeals_badworkouts_nofreetrial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled', models.TextField(max_length=5000, verbose_name='Canceled')),
            ],
        ),
    ]
