# Generated by Django 4.1.7 on 2023-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroses', '0008_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_with', models.TextField(max_length=5000, verbose_name='Go With product')),
            ],
        ),
    ]
