# Generated by Django 4.1.7 on 2023-03-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroses', '0010_notuserfriendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowMuchWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_weight', models.TextField(max_length=5000, verbose_name='Unknown weight')),
            ],
        ),
    ]
